### ISSUE TITLE
Use html to represent H3 in Release Notes

### ISSUE THREAD

**Issue by claireyuw** [milvus-io/milvus-docs#1085]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

Repetitive H3 in the side navigation. Only the set of H3 under the first H2 works.

### Suggestion

Use the syntax `<h3 id="v2.0.0-RC8">Compatibility</h3>` to replace `###`.

Apply to both EN and CN.

**Comment by chris-zilliz** [comment]
Got it. I am handling this.
