### ISSUE TITLE
[ERROR]: Inaccurate documentation description

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus-docs#1125]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

link: https://milvus.io/cn/docs/v2.0.0/performance_faq.md

![image](https://user-images.githubusercontent.com/53512883/141766126-50327022-9c54-4bee-a2be-24ef8913098a.png)

datacoord.segment.maxSize just determines the maximum size of each segment, not the threshold for determining the segment's automatic index construction.

rootcoord.minSegmentSizeToEnableIndex is the threshold value that determines the segment's automatic index construction.

**Comment by YiyunNi** [comment]
PR #1126 #1127
