### ISSUE TITLE
[Suggestion]: Add CLI content in milvus doc's user guide

### ISSUE THREAD

**Issue by czhen-zilliz** [milvus-io/milvus-docs#1189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Topic

![image](https://user-images.githubusercontent.com/83751452/143816623-6fd75654-3995-41d2-ac6c-35957d7aef24.png)

As the pic above,  we have python and node SDK usage in User Guide now. 
**Should we consider to add Milvus-CLI to User Guide?**
We find that CLI and Insight page hide too deep to find. Not good for these products promotion. Besides, it's convenient for user to interact with Milvus by CLI.

**Comment by claireyuw** [comment]
Move Tools out of Admin Guide and make it appear on the first level of sidenav for now. 
Upon GA release, add a CLI tab parallel with Python and Node.js to display corresponding CLI commands for each topic under User Guide. Verify whether all basic operations are supported in CLI with @czhen-zilliz.
