### ISSUE TITLE
v2.0.0 Milvus Limits (limitations.md) Doc Update

### ISSUE THREAD

**Issue by ss892714028** [milvus-io/milvus-docs#1192]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

In this doc
https://milvus.io/docs/v2.0.0/limitations.md#Milvus-Limits
Some of the expressions are inaccurate. 

### Suggestion

In search section

Change:
Output per input -> topk
Input -> target input vectors

In Input per remote procedure call (RPC) section:

The section name is ambiguous: Each RPC input and output are all capped at 512MB.

**Comment by claireyuw** [comment]
@chris-zilliz While fixing this issue, please verify all limitations with @czhen-zilliz to make sure they are up-to-date. 

Make sure to update both EN and CN pages.

**Comment by chris-zilliz** [comment]
Got it. Will do.
