### ISSUE TITLE
v2.0.0 Release Notes (release_notes.md) 

### ISSUE THREAD

**Issue by YiyunNi** [milvus-io/milvus-docs#1265]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

In the v2.0.0-PreGA release note:

1.  Should be "cause search performance to plummet and storage usage to surge" or "cause a slump in search performance and a surge in storage usage".
![截屏2022-01-10 10 52 35](https://user-images.githubusercontent.com/74396087/148713198-24c69246-2d5f-4c79-8cc1-a015b5358ff7.png)

2. What is the difference between "Improvements" and "Other Enhancements"? Can these two sections be combined together?
![截屏2022-01-10 10 56 26](https://user-images.githubusercontent.com/74396087/148713360-bb8ea360-ddb3-442a-8a34-88146bf3c52f.png)

3. I am not quite sure about the relationship between "Automatic Loadbalance" and "Handoff". Can these two be listed separately as two new features?
![截屏2022-01-10 11 01 06](https://user-images.githubusercontent.com/74396087/148713617-e9a37abf-8d1a-4d87-a7f6-495fb50bd2a6.png)

**Comment by LocoRichard** [comment]
@YiyunNi Other Enhancement refers to enhancement made to the system other than performance improvement.

The other two will be fixed soon.
