### ISSUE TITLE
Milvus roadmap needs to be updated

### ISSUE THREAD

**Issue by YiyunNi** [milvus-io/milvus-docs#1272]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

The roadmap is outdated. Please update asap.
![截屏2022-01-11 11 11 35](https://user-images.githubusercontent.com/74396087/148874939-45e17980-80ed-4086-9b86-6cc0ce4196e4.png)

**Comment by LocoRichard** [comment]
Will be fixed along with GA release

**Comment by YiyunNi** [comment]
PR #1309
