### ISSUE TITLE
[ERROR]: `{{tab}}` should not show on the attu_install-docker.md

### ISSUE THREAD

**Issue by jennyli-z** [milvus-io/milvus-docs#1277]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

`{{tab}}` should not show on the attu_install-docker.md, as it is confused.
https://github.com/milvus-io/milvus-docs/blob/v2.0.0/site/zh-CN/userGuide/tools/attu_install-docker.md
![image](https://user-images.githubusercontent.com/93511422/149262602-467c2bb5-c267-49ec-9965-b2a2afe9db60.png)

**Comment by LocoRichard** [comment]
@jennyli-z This is a similar issue like what we talk about earlier. {{tab}} is a placeholder for rendering and currently we cannot delete it.

**Comment by LocoRichard** [comment]
I left a note to redirect people to Milvus.io and web-content repo to checkout the fully rendered tech doc of Milvus in the description and readme.
`This repository is for Milvus technical documentation update and maintenance. Visit Milvus.io or Web content repo for fully rendered documents.`
