### ISSUE TITLE
[QUESTION]: module 'google.protobuf.descriptor' error

### ISSUE THREAD

**Issue by evelynmitchell** [milvus-io/milvus-docs#1362]
### Is your question answered elsewhere?

- [X] searched the existing issues.
- [X] asked MilMil.
- [X] read the [documentation](https://milvus.io/docs).

### What is your question?

When running hello_milvus.py on an Ubuntu 20.04 system I got:

```
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```

### Anything else?

I checked the version of protobuf installes:
```
$ pip3 show protobuf
Name: protobuf
Version: 3.6.1
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author: None
Author-email: None
License: 3-Clause BSD License
Location: /usr/lib/python3/dist-packages
Requires: 
Required-by: grpcio-tools
```
I then checked the version required by pymilvus by looking in requirements.txt:
```
protobuf==3.17.1
```
The needed version was much newer than the installed version, so I upgraded with pip:
```
pip install --upgrade protobuf
```
Verified the upgrade:
```
$ pip3 show protobuf
Name: protobuf
Version: 3.19.4
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author: None
Author-email: None
License: 3-Clause BSD License
Location: /home/efm/.local/lib/python3.8/site-packages
Requires: 
Required-by: grpcio-tools
```

And then was able to successfully run hello_milvus.py

**Comment by LocoRichard** [comment]
Hi @evelynmitchell , Thank you for your report. I have update this issue to PyMilvus FAQ via https://github.com/milvus-io/pymilvus/pull/886, and it will soon be on `https://milvus.io/api-reference/pymilvus/v2.0.0/faq.html`.
