### ISSUE TITLE
[ERROR]: 删除实例后，未生效。

### ISSUE THREAD

**Issue by LiAI-tech** [milvus-io/milvus-docs#1370]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

![image](https://user-images.githubusercontent.com/54132151/154031862-adfc1ae5-f20b-4e83-b620-f2256b412845.png)

**Comment by LocoRichard** [comment]
Hi@LiAI-tech , this is the repo for Milvus Tech docs. I am gonna transfer this issue the Milvus code repo, where your question about Milvus usage can get help.

**Comment by LocoRichard** [comment]
Hi @LiAI-tech ,  when you call `num_entities` after deletion, you will not likely to get an accurate result of the number of entities in the collection since it is logical deletion. But you can verify if the deletion is successful by query the vectors you have deleted.

**Comment by LiAI-tech** [comment]
Thanks for your help, @LocoRichard .How to physically delete?

**Comment by LocoRichard** [comment]
> Thanks for your help, @LocoRichard .How to physically delete?

You can [compact data](https://milvus.io/docs/v2.0.0/compact_data.md) if you want to clear up the outdated data. But deleted data within the [Time Travel](https://milvus.io/docs/v2.0.0/timetravel.md) span will not be compacted to guarantee that you can retrieve the data after accidental deletion. And lastly, in current release, data compaction will not correct the `num_entities` either.
