### ISSUE TITLE
v2.0.0 Delete Entities (delete_data.md) Doc Update

### ISSUE THREAD

**Issue by LiAI-tech** [milvus-io/milvus-docs#1381]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

Deleted entities can still be retrieved immediately after the deletion if the consistency level is set lower than Strong.
How to set consistency level?

**Comment by claireyuw** [comment]
@LiAI-tech You might find this blog useful: https://milvus.io/blog/2022-1-27-milvus-2-0-a-glimpse-at-new-features.md#Consistency-level

**Comment by LiAI-tech** [comment]
@claireyuw Thanks.That explains a lot!
