### ISSUE TITLE
v2.0.0 布尔表达式语法规则 (boolean.md) Doc Update

### ISSUE THREAD

**Issue by Peeeng** [milvus-io/milvus-docs#1395]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

为什么我在使用delete的时候，只支持in的表达式，使用其他表达式（>   <   not in  == 等）均报错“invalid plan node type”，是我使用方式不对吗？
![image](https://user-images.githubusercontent.com/33120546/155670438-e16e982e-f25c-4630-bd22-3fb0dd46257d.png)
![image](https://user-images.githubusercontent.com/33120546/155670463-6573a176-426a-4e8a-aec6-b039bf5cd38e.png)

### Suggestion

帮忙解释下这个问题，或者这是个bug？

**Comment by LocoRichard** [comment]
Hi @Peeeng , Milvus only supports deleting entities with primary key specified clearly in the expression. It can be achieved only with operator `in`. Obscure operators such as `<` or `>` can be only used in query. Thank you so much for bring up this issue, I shall add a note in the document.

**Comment by Peeeng** [comment]
Thank you for your help
