### ISSUE TITLE
v2.0.x Release Notes (release_notes.md) Doc Update

### ISSUE THREAD

**Issue by ThyeeZz** [milvus-io/milvus-docs#1403]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

![image](https://user-images.githubusercontent.com/41352919/155865616-4dc91d8f-568f-49e5-a4c3-9f88524bf4ec.png)
an extra piont or a missed 0?

**Comment by LocoRichard** [comment]
Milvus 2.0 is the general publication release for current version.
