### ISSUE TITLE
expr:grouping

### ISSUE THREAD

**Issue by lucky-zhao** [milvus-io/milvus-docs#1406]
### Is your question answered elsewhere?

- [X] searched the existing issues.
- [X] asked MilMil.
- [X] read the [documentation](https://milvus.io/docs).

### What is your question?

<img width="870" alt="image" src="https://user-images.githubusercontent.com/45654758/155953509-6d384e0c-631b-4d4e-a4f6-39481b56a641.png">

how to use ,please.
give me a demo;

java code:

      R<SearchResults> search = milvusRepository.search(collectionName, ID_FIELD, "()", VECTOR_FIELD, "{\"nprobe\":10}", lists);

### Anything else?

give me a demo

**Comment by LocoRichard** [comment]
Hi, @lucky-zhao 
```
LogicalExpr = LogicalExpr BinaryLogicalOp LogicalExpr 
              | UnaryLogicalOp LogicalExpr
              | "(" LogicalExpr ")"
              | SingleExpr;       
```
Like the description in the doc, when you want to combine a group of logical expressions, you will need to write it like this:
`"("LogicalExpr_1" BinaryLogicalOp "LogicalExpr_1")"`. For instance, `"("scalar_1 > 100" and "scalar_2<300")"`.

**Comment by lucky-zhao** [comment]
In Java, how to call it?

**Comment by lucky-zhao** [comment]
In Java, how to call it?
For example, if I want to repeat through name, how should I write it?

<img width="792" alt="image" src="https://user-images.githubusercontent.com/45654758/155967197-fbfebaa3-64e8-415d-b8be-f2d37ea56f30.png">

**Comment by lucky-zhao** [comment]
What I want to do now is to redo according to a certain field during query, which is a bit like SQL: select * from tablename group by name

**Comment by LocoRichard** [comment]
Hi @lucky-zhao ，I am sorry that Milvus does not support `group by` function currently. 

Here grouping does not refer to `group by` function in SQL, it's a combination of different expressions.

I hope this would answer your question.

**Comment by LocoRichard** [comment]
For issues concerning Milvus Usage, please file the issue in `https://github.com/milvus-io/milvus`. 
Closing the issue.
