### ISSUE TITLE
[QUESTION]: efConstruction参数问题

### ISSUE THREAD

**Issue by henyaoyuan** [milvus-io/milvus-docs#1426]
### Is your question answered elsewhere?

- [X] searched the existing issues.
- [X] asked MilMil.
- [X] read the [documentation](https://milvus.io/docs).

### What is your question?

您好，HNSW算法中，efConstruction是什么意思，与检索效果有什么关系，能解释下吗，谢谢！

### Anything else?

no

**Comment by LocoRichard** [comment]
@henyaoyuan 
efConstruction 指的是构建索引时动态候选元素集合大小，既在每一层中搜寻最近邻的点的个数。
通常来说，efConstruction 越大，索引构造时间越长，index accuracy 相对（在一定范围内）越高。

**Comment by LocoRichard** [comment]
For issues concerning Milvus Usage, please file the issue in `https://github.com/milvus-io/milvus`. 
We'd encourage all member of Milvus community to file issues with English so that all members could understand and share their opinions.
Closing the issue.
