### ISSUE TITLE
v2.0.x Install Milvus SDK (install-pymilvus.md) Doc Update

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus-docs#1441]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

link: https://milvus.io/docs/v2.0.x/install-pymilvus.md

![image](https://user-images.githubusercontent.com/53512883/158288954-a6d05e53-5560-49b9-9684-5a5cdc420467.png)

It should be "3.7.1" not "3.71".

**Comment by JackLCL** [comment]
The English website also needs to be revised.

**Comment by LocoRichard** [comment]
> The English website also needs to be revised.

I'd fixed it directly on the main branch, thus you won't see it in the PR.
