### ISSUE TITLE
[ERROR]: Miss the consistency attributes of collection in version v2.0.0

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus-docs#1444]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

![image](https://user-images.githubusercontent.com/12268675/158762950-45182628-182e-40c5-8ee5-b5ae9d85f413.png)

### Suggestion

introduce this feature in attributes

**Comment by LocoRichard** [comment]
We will soon remake the whole API docs, and this will be fixed along with the remaking.
