### ISSUE TITLE
[Suggestion]: Improve the project ignore list and clean up unnecessary files

### ISSUE THREAD

**Issue by soulteary** [milvus-io/milvus-docs#1445]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

Hello maintainers 👋

I found some unnecessary junk files in the project, eg: 

```bash
.DS_Store
site/.DS_Store
site/en/userGuide/.DS_Store
site/en/userGuide/tools/.DS_Store
site/zh-CN/.DS_Store
site/zh-CN/userGuide/.DS_Store
site/zh-CN/userGuide/tools/.DS_Store
```

### Suggestion

In order to avoid more similar OS-generated temporary files mixed into the repository in the future, I think we should improve the contents of the ignore file.

### Anything else?

Later, I will submit a PR to complete the ignore list of this project, hope it can help you.

**Comment by soulteary** [comment]
I made some adjustments and cleaned up the extra junk files in the repository, hope it can help you :D

https://github.com/milvus-io/milvus-docs/pull/1446

**Comment by LocoRichard** [comment]
Thank you, merging the PR and closing the issue
