### ISSUE TITLE
[ERROR]: The `Data consistency` number in the comparison document is wrong, some content in the Chinese document needs to be updated

### ISSUE THREAD

**Issue by soulteary** [milvus-io/milvus-docs#1448]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

The Data consistency data in the comparison document is wrong, some content in the Chinese document needs to be updated.

### Suggestion

I submitted a simple PR to fix:

https://github.com/milvus-io/milvus-docs/pull/1447

**Comment by LocoRichard** [comment]
Thank you for fixing this problem, closing the issue
