### ISSUE TITLE
[Proposal]: More modern documentation site

### ISSUE THREAD

**Issue by soulteary** [milvus-io/milvus-docs#1450]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

hello maintainer 👋

Our current site is based on `gatsby` and looks like it's been a while. Gatsby is a great project, but it's not friendly to contributors.

Compared to golang-based SSG tools, it is difficult for contributors to start or preview our current documentation site without installing or configuring any development environment.

If contributors can preview changes to the documentation before submitting a GitHub PR, I think this can reduce a lot of problems that are discovered after the site is redeployed after submitting the code.

And, the performance of the current website, for a documentation site, also seems to be a little slow.

### Suggestion

If we're willing to tweak the documentation site building mode, maybe we can try Hugo, or even other dedicated documentation generation tools. I believe this will bring about a **great improvement** in contribution experience and browsing speed.

If we are currently not suitable to make changes to the way the site is built, then I think maybe I can provide a docker image for contributors to quickly local preview document changes.

Related tool links

  - Hugo: https://github.com/gohugoio/hugo
  - MkDocs: https://www.mkdocs.org/
  - Read the docs: https://github.com/readthedocs/readthedocs.org
  - ReadMe (SaaS) https://readme.com/

**Comment by shanghaikid** [comment]
> If contributors can preview changes to the documentation before submitting a GitHub PR, I think this can reduce a lot of problems that are discovered after the site is redeployed after submitting the code.

**If the user finds the text is displayed incorrectly on the website, he can file an issue in the website repo. Content is just content, it shouldn't be related with the UI layer.** 

> And, the performance of the current website, for a documentation site, also seems to be a little slow.
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/185051/158929897-701f0597-00a3-49cc-8eec-4a025230168a.png"> 

**So far, I think the performance is good as long as you have the good network connection, we are planning to move some resource to the CDN, hopefully it will solve your problem.** 

> If we are currently not suitable to make changes to the way the site is built, then I think maybe I can provide a docker image for contributors to quickly local preview document changes.
Yes, we are not suitable. Docker image is a good option, we will try it. Thanks.

**Comment by soulteary** [comment]
Thank you for your reply. @shanghaikid  Here are **a few different** points of view:

I agree with the separation of content and UI, but for users, being able to intuitively preview their own contributions **is better** than seeing them after being reviewed and automatically deployed by CI.

For the users of milvus, we **don't** actually pay attention to the official website, we **will pay more attention to** the presentation experience of the documentation site and its directory. For this example, we should take a look at the performance of the documentation page.

I tested the page with the same tool as you:

![image](https://user-images.githubusercontent.com/1500781/158937661-68ee65e1-ad9e-4a64-911c-4a6fc2e2224f.png)

Even with a good performance testing tool on the Internet, it takes **nearly 1s** to see the content after seeing the "Overview" page that does not contain relatively large-sized image resources. Before that, the page remained on a white screen for **a long time**.

Under normal circumstances, it **is difficult** for normal users to obtain such a good network. It is not difficult to imagine that the experience of most users when using documents may not be satisfactory.

This is the reason why I raised the above issue feedback and suggested to replace the SSG tool.

**Comment by soulteary** [comment]
I have just conducted several tests using a relatively large network quality evaluation tool in China (to avoid caching affecting the average access quality)

It can be seen that the HTML content of the page cannot be downloaded at a relatively fast speed in most areas. (Test GET to get only page HTML document content)

![image](https://user-images.githubusercontent.com/1500781/158939677-3fc0e1bb-d3c4-4675-af32-23a7ce25f670.png)

These test servers are all from cloud servers in China. Compared with most users, they also have very good network quality. In other words, the network quality of ordinary users **cannot be** compared with them.

The access speed in most areas is very slow, and even some areas have been canceled due to time-out test results, and are displayed in gray on the map.

![image](https://user-images.githubusercontent.com/1500781/158939721-9ff6b327-28cc-4f53-acfd-ff5d51ff6e0a.png)

This is **just** the download of the homepage HTML document. Most regions take 2s~4s, and even some regions have access time close to 10s. Don’t forget, there are still some regions without test data, because **it is too slow.**


Imagine that if the document page opened by the user contains a lot of pictures, the browser will turn around again and again, and the process will be blank. Is this friendly enough for most users, especially Chinese users?

I wrote this much, **not to argue right or wrong, just to point out where the maintainers may have missed,** because a lot of times, we will overlook some obscure facts because of previous experience, and these problems will lead to more people playing milvus not smooth.




The complete data report can be seen here, I hope it can help you make decisions:
http://www.17ce.com/site/http/20220318_e0402f50a67511ec89545fe60f9332a6:1.html


Well, I tried my best to share what I saw with you, I know maintainers do a lot of things every day, thank you for your work, and we can use a great software.

If you have any suggestions and ideas, or if I am wrong, please point them out. Looking forward to continued communication.

@shanghaikid

**Comment by soulteary** [comment]
To be more objective, I tried another large test site, do the same test was done on the overview document:

![image](https://user-images.githubusercontent.com/1500781/158941258-4ea01a83-d708-4bb0-a215-99cbf3f597af.png)

This time the test results seem to be even worse

The complete data report can be seen here
https://www.boce.com/http/milvus.io/4d4ab9144d8bc945d8c3dd4cb2406f59.html

**Comment by shanghaikid** [comment]
Yes, the site is not fast in china, because it is deployed in US, and we our strategy is always global first. Anyway, hopefully CDN can help, someone is looking at this.

**Comment by shanghaikid** [comment]
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/185051/159008956-7a6e244d-42b2-4439-ad40-64e3a80f16e4.png">
We made some optimization, now  it takes only 529ms to see the page. 
Hopefully in the next days, the CDN will take effect.

**Comment by soulteary** [comment]
**Thanks for the update, the experience has indeed changed significantly.** 🎉

I hope that CDN will be helpful for the improvement of network quality in China. 😅

**Comment by xiaofan-luan** [comment]
Did we do the change already? seems the homepage is opened much faster

**Comment by shanghaikid** [comment]
> Did we do the change already? seems the homepage is opened much faster

Yes, we did, but we are waiting for the  LF AI guys to apply, because the dns system is managed by him.
