### ISSUE TITLE
[ERROR]: doc error

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus-docs#1475]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

link: https://milvus.io/blog/deep-dive-4-data-insertion-and-data-persistence.md

![image](https://user-images.githubusercontent.com/53512883/162377469-df84fab7-e316-4300-8eec-58a23ba1a073.png)

It should be "data node".

**Comment by YiyunNi** [comment]
Fixed. https://github.com/milvus-io/community/pull/140
