### ISSUE TITLE
[ERROR]: Nothing shows for the link `Building Milvus from Source Code`

### ISSUE THREAD

**Issue by jennyli-z** [milvus-io/milvus-docs#1504]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

![image](https://user-images.githubusercontent.com/93511422/167363006-d2593b4a-e54e-4a68-8b13-625f305124b3.png)
https://milvus.io/docs/v2.0.x/operational_faq.md#What-if-I-failed-to-pull-the-Milvus-Docker-image-from-Docker-Hub 
click the link on the text `Building Milvus from Source Code` 
it will goes to https://github.com/milvus-io/milvus/blob/master/INSTALL.md
and show "Page not found"

### Suggestion

Should have the right install link

**Comment by YiyunNi** [comment]
Closing with PR #1505
