### ISSUE TITLE
[ERROR]: The description about Superstructure and Substructure is not correct.

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus-docs#1523]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

link: 
https://milvus.io/docs/v2.0.x/metric.md#Superstructure
https://milvus.io/docs/v2.0.x/metric.md#Substructure

![image](https://user-images.githubusercontent.com/53512883/169019681-869a2f54-2667-43d1-bab7-2bcbc22cea85.png)

The similarity of superstructure and substructure is either 0 or 1. Either yes or no, there will be no intermediate results. The description on the official website is incorrect.

### Suggestion

N/A

### Anything else?

N/A

**Comment by YiyunNi** [comment]
Closed with PR #1524
