### ISSUE TITLE
[ERROR]: Remove outdated roadmap.md

### ISSUE THREAD

**Issue by claireyuw** [milvus-io/milvus-docs#1538]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

[Milvus Roadmap](https://milvus.io/docs/roadmap.md) page has been replaced with an outlink to [LF AI Confluence page](https://wiki.lfaidata.foundation/display/MIL/Milvus+2.X+Roadmap+and+Time+schedule) but still appears in Google search results. 

### Suggestion

Remove this file.

**Comment by YiyunNi** [comment]
Closed with PR #1556
