### ISSUE TITLE
[ERROR]: Coordinator scale out isn't supported

### ISSUE THREAD

**Issue by john-h-luo** [milvus-io/milvus-docs#1541]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

On the page https://milvus.io/docs/v2.0.x/install_cluster-ansible.md#:~:text=If%20you%20need%20to%20scale%20out%20Milvus%20nodes%20and%20coordinators, there's a misconception about scale out coordinators. Please remove from this paragraph anything that is related to coordinator scale out.

### Suggestion

Scale out Milvus nodes
If you need to scale out Milvus nodes, you can follow the steps below to add new docker hosts directly in Ansible playbook.

Prepare host resources as requested in the prerequisites.
Ensure connectivity to the network and host names can be resolved.
Add the new host to the corresponding section in the inventory.ini file. More specifically, add the host name of the new node in the node section as shown in the example below.

**Comment by YiyunNi** [comment]
Closed with PR #1558
