### ISSUE TITLE
[ERROR]: Broken link in Install-node.md

### ISSUE THREAD

**Issue by claireyuw** [milvus-io/milvus-docs#1561]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Issue

![image](https://user-images.githubusercontent.com/83751381/176119855-6418af62-6a5a-4f44-a2ee-2968f0520b51.png)

This link should be https://milvus.io/api-reference/node/v2.0.2/About.md

### Suggestion

Please also conduct a universal search to make sure this does not exist elsewhere in the documentation.

**Comment by RosieZhang12** [comment]
PR#1564
