### ISSUE TITLE
Add curl commands in user guides

### ISSUE THREAD

**Issue by claireyuw** [milvus-io/milvus-docs#1563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Topic

Milvus 2.1 supports RESTful API (beta) and this needs to be reflected in user guides. Please add a curl tab that's parallel with  Python, Java, Go, Node.js, and CLI. 
Commands will be provided by @haorenfsa 

### Type

how-to doc

**Comment by RosieZhang12** [comment]
Closed with PR #1572
