### ISSUE TITLE
[ERROR]: docker-compose cannot deploy a true milvus distributed cluster.

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus-docs#1574]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

link: https://milvus.io/docs/v2.0.x/install_cluster-docker.md

Docker-compose cannot deploy Milvus distributed clusters across machines, and can only be used in test environments. It is not recommended that users deploy Milvus distributed clusters in this way in production environments. This information needs to be noted in the documentation.

**Comment by RosieZhang12** [comment]
PR#1577
