### ISSUE TITLE
[ERROR]: The PyMilvus requirements should be Python 3.6 or later

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus-docs#1590]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

In this page:
https://milvus.io/docs/v2.0.x/install-pymilvus.md

The Requirement section:
`Python 3 (3.7.1 or later) is required.`
Should be changed to:
`Python 3.6 or later is required.`

**Comment by YiyunNi** [comment]
Closed with PR #1592
