### ISSUE TITLE
[ERROR]: Hardware requirements need to be updated

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus-docs#1597]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

In this page: https://milvus.io/docs/v2.0.x/prerequisite-docker.md
In section "Hardware requirements", we say "Current version of Milvus does not support AMD and Apple M1 CPUs.", actually current milvus can support Apple M1 CPI, so we need to update the sentence to be "Current version of Milvus does not support AMD CPUs"

**Comment by YiyunNi** [comment]
Closed with PR #1598
