### ISSUE TITLE
[ERROR]: Remove IVF_HNSW section since it is no longer supported

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus-docs#1616]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

In this page:
https://milvus.io/docs/v2.0.x/index.md

The IVF_HNSW is no longer supported, we should remove the IVF_HNSW section from this page.

**Comment by YiyunNi** [comment]
Closed with PR #1617
