### ISSUE TITLE
[Suggestion]: add more detail about how to connect to milvus

### ISSUE THREAD

**Issue by weiliu1031** [milvus-io/milvus-docs#1730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Topic

we can reuse the chapter https://milvus.io/docs/v2.1.x/manage_connection.md#Manage-Milvus-Connections, but add more detail about how to connect to milvus.

### Type

how-to doc

### Outline

1. with a milvus cluster/standalone, how to get the ip and port to connect
2. does different access method has same port, such as curl and pymilvs.

**Comment by songxianj** [comment]
I recently updated [Install Milvus (Helm)](https://milvus.io/docs/v2.1.x/install_standalone-helm.md#Connect-to-Milvus) with clearer guidelines on port management. Perhaps it'll be of help. @RosieZhang12

**Comment by RosieZhang12** [comment]
Pr #1751 #1752
