### ISSUE TITLE
[ERROR]: Empty link on membership page

### ISSUE THREAD

**Issue by jennyli-z** [milvus-io/milvus-docs#1769]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

https://github.com/orgs/milvus-io/teams/tsc is an empty link on membership page
![2L5APHL13W](https://user-images.githubusercontent.com/93511422/186802065-d5784b9a-1caf-45bd-85aa-2c0aa93967ac.jpg)
https://milvus.io/community/membership.md

**Comment by YiyunNi** [comment]
Thanks for the suggestion! This page is not maintained will be go through an overhaul later. I have removed the broken link temporarily to fix this issue. @jennyli-z . See PR: https://github.com/milvus-io/web-content/pull/739
