### ISSUE TITLE
[Suggestion]: Document collection compaction for Python

### ISSUE THREAD

**Issue by mausch** [milvus-io/milvus-docs#1797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Topic

Data compaction is described in https://milvus.io/docs/v2.1.x/compact_data.md?python#Compact-data-manually
However the compaction functions are not listed in https://milvus.io/api-reference/pymilvus/v2.1.1/Collection/Collection().md

### Type

reference doc

**Comment by YiyunNi** [comment]
Hi @mausch , thanks for your suggestion. I have added compaction() to the Python API reference. See this [PR](https://github.com/milvus-io/web-content/pull/746)
