### ISSUE TITLE
[ERROR]: Error link in install c# sdk.

### ISSUE THREAD

**Issue by weianweigan** [milvus-io/milvus-docs#2297]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

Current [c# sdk install guide](https://github.com/milvus-io/milvus-docs/blob/v2.2.x/site/en/getstarted/install_SDKs/install-csharp.md) linked java sdk api reference.

![image](https://github.com/milvus-io/milvus-docs/assets/25452811/c677039b-d17f-4617-aa44-88ec230f1c77)

**Comment by aniketh-varma** [comment]
Hey @claireyuw, can I work on this issue as a part of my Hacktoberfest contributions?

**Comment by weianweigan** [comment]
#2353
