### ISSUE TITLE
[ERROR]: Documentation search (using algolia) for v2.4.x version is broken

### ISSUE THREAD

**Issue by msmygit** [milvus-io/milvus-docs#2477]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

Today, when someone navigates to https://milvus.io/docs and uses the top left search bar to search for contents, nothing shows up.

<img width="923" alt="image" src="https://github.com/milvus-io/milvus-docs/assets/19366623/5826e4aa-455a-4910-a4fb-3c71e4557f3e">

FWIW, when I switch to `v2.3.x`, the search bar works fine. See below,
<img width="995" alt="image" src="https://github.com/milvus-io/milvus-docs/assets/19366623/18a11fa1-2982-45c0-b477-e3c6e08bb5c3">

So a very recent update no 2024-03-20 has broken the docs search.

Thank you in advance for fixing it!

**Comment by liyun95** [comment]
Thank you for the feedback. The issue has been resolved, so I will go ahead and close this.
