### ISSUE TITLE
[Suggestion]: tls.md should provide detail for both 1-way & 2-way tls

### ISSUE THREAD

**Issue by haorenfsa** [milvus-io/milvus-docs#2514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Topic

# Encryption in Transit

### Type

None

**Comment by liyun95** [comment]
thanks for your feedback. pls check out our revised doc: https://milvus.io/docs/tls.md#Set-up-a-Milvus-server-with-TLS. hope it helps :)
