### ISSUE TITLE
[Suggestion]:  Distance metrics didn't include cosine metrics and binary embedding

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus-docs#2526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Topic

Currently the range search document only support ip and L2 metrics.
But I think we should add cosine metrics, and maybe binary embedding metrics later once binary embedding support range search

### Type

None

**Comment by liyun95** [comment]
this issue has been fixed in https://github.com/milvus-io/milvus-docs/pull/2686. see https://milvus.io/docs/single-vector-search.md#Range-search for more details.
