### ISSUE TITLE
[ERROR]: 'make' command not working while trying to work with milvus repo

### ISSUE THREAD

**Issue by RajnandiniG** [milvus-io/milvus-docs#2553]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

Clone Milvus repo and build.

# Clone github repository.
$ git clone https://github.com/milvus-io/milvus.git

# Install third-party dependencies.
$ cd milvus/
$ ./scripts/install_deps.sh

# Compile Milvus.
$ make

### Anything else?

make[1]: Entering directory '/users/sharmara/milvus-2.4.0/cmake_build'
make[1]: *** No rule to make target 'install'.  Stop.
make[1]: Leaving directory '/users/sharmara/milvus-2.4.0/cmake_build'
make: *** [Makefile:228: build-cpp] Error 1

**Comment by liyun95** [comment]
thanks for reporting this issue. since this does not appear to be a doc issue, i'd suggest opening a new issue in the main Milvus repository at https://github.com/milvus-io/milvus/issues. the Milvus team will be better able to assist you there :)
