### ISSUE TITLE
[ERROR]: Minor Issue with Langchain Integration Docs

### ISSUE THREAD

**Issue by devesh-2002** [milvus-io/milvus-docs#2569]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

From the docs, [Integration with langchain](https://milvus.io/docs/integrate_with_langchain.md). I was trying to install via the docs : 
```
! python -m pip install --upgrade pymilvus langchain langchain-core langchain-community langchain-openai langchain_text_splitters openai tiktoken
```
but it gave error
```
ModuleNotFoundError: No module named 'bs4'
```
Also, the second issue, we have imported ```ChatPromptTemplate```, while used ```PromptTemplate```, so it gave an error.
```
NameError: name 'PromptTemplate' is not defined
```
Should I rectify these errors in the docs?

### Suggestion

For the first issue I had to install ```bs4```.
For second issue I changed : 
```
from langchain_core.prompts import ChatPromptTemplate
```
to
```
from langchain_core.prompts import PromptTemplate
```

**Comment by zc277584121** [comment]
@devesh-2002 Thank you for your suggestion. We have updated this document and these issues have currently been solved.
![image](https://github.com/milvus-io/milvus-docs/assets/17022025/83f139f1-d0c5-49cf-b994-f20d93e155af)
![image](https://github.com/milvus-io/milvus-docs/assets/17022025/f9a74785-6044-4f6e-ad7f-b98c662498ad)
