### ISSUE TITLE
[QUESTION]: Load error

### ISSUE THREAD

**Issue by deict** [milvus-io/milvus-docs#2581]
### Is your question answered elsewhere?

- [X] searched the existing issues.
- [X] read the [documentation](https://milvus.io/docs).

### What is your question?

 1 GPU  
memory:181G
data bulk：33905126
DIM：384
INDEX：IVF_FLAT

run load() error，don't know why？Please take a look, thanks.

Look forward to your reply.
[python_error.txt](https://github.com/milvus-io/milvus-docs/files/15374947/python_error.txt)
[milvus_warn1.log](https://github.com/milvus-io/milvus-docs/files/15374998/milvus_warn1.log)

**Comment by liyun95** [comment]
thanks for reporting this issue. since this does not appear to be a doc issue, i'd suggest opening a new issue in the main Milvus repository at https://github.com/milvus-io/milvus/issues. the Milvus team will be better able to assist you there :)
