### ISSUE TITLE
[Suggestion]: How to enable authentication of Milvus in Docker instead of Docker Compose

### ISSUE THREAD

**Issue by ghost** [milvus-io/milvus-docs#2658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Topic

I install Milvus with [standalone_embed.sh](https://raw.githubusercontent.com/milvus-io/milvus/master/scripts/standalone_embed.sh). 
How could I enable the authentication? It would be best if you could add the procedures in [Authenticate User Access](https://milvus.io/docs/authenticate.md).

### Type

tutorials

**Comment by LoveEachDay** [comment]
@Ywandung-Lyou It's recommended to deploy milvus with `docker-compose` if you'd like to change milvus configurations on the fly. 

Read more from: https://milvus.io/docs/configure-docker.md?tab=component
