### ISSUE TITLE
[ERROR]: The warmup configuration needs to be updated

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus-docs#2687]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

2.4 The documentation for the warmup configuration has not been updated. 
![3aa453fc-6f35-45b3-ade7-1d7d76eae725](https://github.com/milvus-io/milvus-docs/assets/48523564/cafcba37-f19f-4a64-8885-d89007598876)

https://milvus.io/docs/chunk_cache.md#Configure-Chunk-Cache 
![d077b87b-3da4-4319-b20b-b7e09db4185e](https://github.com/milvus-io/milvus-docs/assets/48523564/c93ee744-8a3c-413b-8f0e-76323ccf1177)

**Comment by liyun95** [comment]
#2688
