### ISSUE TITLE
Binary field index type error

### ISSUE THREAD

**Issue by nameczz** [milvus-io/milvus-docs#310]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

**Where is the error**
https://milvus.io/docs/v2.0.0/metric.md#binary

**How would you like to improve it**
In binary field, index should be BIN_FLAT and BIN_IVF_FLAT

**Screenshots**

![image](https://user-images.githubusercontent.com/20559208/126478256-31138600-4cfa-4c75-a6d8-79ae270a5d2a.png)

**Comment by PahudPlus** [comment]
@LocoRichard
