### ISSUE TITLE
[ERROR] milvus-docs/site/en/getstarted links broken

### ISSUE THREAD

**Issue by jgardner04** [milvus-io/milvus-docs#338]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

**Where is the error**
I am trying to follow the instructions to Install Milvus and following the User guide on https://github.com/milvus-io/milvus-docs/tree/v2.0.0/site/en/getstarted

It looks like all the links here are broken.

**How would you like to improve it**

**Screenshots**

**Comment by LocoRichard** [comment]
Hi @jgardner04 , thank you for your report. This readme.md is outdated and we were just about to change it. You can refer to [Milvus.io](https://milvus.io/docs/v2.0.0/prerequisite-docker.md) for a step-by-step guide.
