### ISSUE TITLE
[Suggestion] Style for html and markdown tables are inconsistent.

### ISSUE THREAD

**Issue by YiyunNi** [milvus-io/milvus-docs#387]
**Where is the issue:**
https://milvus.io/docs/v2.0.0/hybrid.md

On the same webpage, the table written in **markdown** format is displayed as:
![截屏2021-08-17 14 39 50](https://user-images.githubusercontent.com/74396087/129676409-46f8a156-ba3a-4270-955e-d12e69c34abb.png)

While the other table written in **html** format is displayed as:
![截屏2021-08-17 14 42 51](https://user-images.githubusercontent.com/74396087/129676602-865a5216-ebad-480b-85cf-c8a7c03d1ddc.png)

I have to write the second table in the html format because there is a symbol "||"" that can not be properly recognized in the markdown format.

**Comment by shanghaikid** [comment]
For "||", Can you try "\|\|"  instead  ?

**Comment by YiyunNi** [comment]
This works! Thank you.
