### ISSUE TITLE
[Suggestion] Add Tutorials 

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus-docs#500]
Although milvus has a bootcamp repo,  but I would like to see a separate menu item in the menu tree.  More exposure  is always better.

For example: 

```
- Reference
- Tutorials 
  - Image similarity search
  - Question answer system 
  - Recommend system
  - Video similarity search
  - Audio search system
  - Molecular Similarity Search
  - DNA Sequence Classification
```
- FAQ

Each page can have an introduction and a demo link and repo link to our bootcamp page.

**Comment by YiyunNi** [comment]
I will add the external links first. Individual pages with the introduction with by added gradually when the content is ready.

**Comment by YiyunNi** [comment]
PR #545 #541 #534 #533
