### ISSUE TITLE
[Suggestion] Need detail documentation about supported data type 

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus-docs#519]
When creating a collection, user is asked to create a schema, in a schema, each field has a data type, but there is no detailed information about supported types. 

And also we need to tell user how to write data types  in different kind of language. 

In milvus Grpc proto file, it defines 10 data types. but not all of them are supported yet. 

please confirmed before write this docs. 
 // enum DataType {
  //   None = 0;
  //   Bool = 1;
  //   Int8 = 2;
  //   Int16 = 3;
  //   Int32 = 4;
  //   Int64 = 5;
  //   Float = 10;
  //   Double = 11;
  //   String = 20;
  //   BinaryVector = 100;
  //   FloatVector = 101;
  // }

**Comment by claireyuw** [comment]
Yes, we were just talking about adding schema docs last week after studying Weaviate docs. Will consolidate next steps with @xiaofan-luan

**Comment by LocoRichard** [comment]
Fixed via #585 , closing the issue
