### ISSUE TITLE
[Suggestion]Add related_key to doc front-matter where applicable

### ISSUE THREAD

**Issue by claireyuw** [milvus-io/milvus-docs#522]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

**Is there anything that's missing or inappropriate in the docs? Please describe.**

Most doc pages are missing a related_key field in front-matter.

**Describe your suggestion**

Choose **one** suitable keyword from the [Google doc](https://docs.google.com/document/d/1d07zPm6Ltr8UxY3CwOowGSjPC9Btd9BOUqociBwoJU4/edit?usp=sharing)  and add it to the front-matter of each applicable page.

> Kindly note that we have listed **several** related keywords (marked in red) in the Google doc. Please only choose **the most relevant one** and add it to the front matter.

A good example would be: [see screenshot](https://zilliz-cms.s3.us-west-2.amazonaws.com/2021_09_22_14_30_24_0044426f43.png?161649)

**Additional reference**
https://docs.google.com/document/d/1d07zPm6Ltr8UxY3CwOowGSjPC9Btd9BOUqociBwoJU4/edit?usp=sharing

**Comment by kartikcho** [comment]
I'd like to take this up!

**Comment by YiyunNi** [comment]
@kartikcho Thanks for you interest in contributing to Milvus! I have assigned this issue to you.
