### ISSUE TITLE
[ERROR] PyMilvus-ORM API Reference does not appear in sidebar

### ISSUE THREAD

**Issue by NotRyan** [milvus-io/milvus-docs#527]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

**Where is the error**
What is the URL/path of the document related to this issue?
https://milvus.io/docs/home
Under the "API Reference" section of the sidebar, the only documentation visible is the Node documentation. 
**How would you like to improve it**
Re-add the PyMilvus API documentation to the sidebar
**Screenshots**
![Screen Shot 2021-08-30 at 5 31 44 PM](https://user-images.githubusercontent.com/5742796/131423313-fc6adf17-2ef7-47e8-8de8-9011a2319e64.png)

Tested on two different browsers; pymilvus API reference does not appear.

If this change was intentional, then this issue can be closed and ignored.

**Comment by LocoRichard** [comment]
issue fixed. Closing the issue.
