### ISSUE TITLE
[ERROR] Should be pymilvus for rc5 instead of pymilvus-orm

### ISSUE THREAD

**Issue by jaelgu** [milvus-io/milvus-docs#528]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

**Where is the error**
What is the URL/path of the document related to this issue?
https://milvus.io/docs/v2.0.0/example_code.md
<img width="737" alt="Screen Shot 2021-08-31 at 9 52 50 AM" src="https://user-images.githubusercontent.com/86251631/131428813-2f34353f-2bb7-4aa3-8c07-3bf8639f21a3.png">
Should be "pymilvus" instead of all "pymilvus-orm" since 2.0.0rc5. According to dev team, pymilvus-orm is merged to pymilvus. Please confirm with them.

**How would you like to improve it**
Replace all "pymilvus-rc5" with "pymilvus"

**Screenshots**

**Comment by jaelgu** [comment]
Also https://milvus.io/docs/v2.0.0/connect.md to be updated as well:
```
from pymilvus_orm import connections
```

**Comment by LocoRichard** [comment]
@jaelgu thank you, working on it.
