### ISSUE TITLE
[Suggestion]Translate tutorials-video_similarity_search.md into CN

### ISSUE THREAD

**Issue by YiyunNi** [milvus-io/milvus-docs#548]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

**Is there anything that's missing or inappropriate in the docs? Please describe.**
video_similarity_search.md

**Describe your suggestion**
CN translation needed.

**Additional reference**
Machine translation post editing (MTPE) is okay, but pure machine translation will not be accepted.
_You should have a certain level of proficiency in both Chinese and English in order to take this issue._

**Comment by Aryamanz29** [comment]
I would like to work on this @YiyunNi
