### ISSUE TITLE
[Suggestion] Translate tutorial - question_answering_system.md into CN

### ISSUE THREAD

**Issue by YiyunNi** [milvus-io/milvus-docs#555]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

**Is there anything that's missing or inappropriate in the docs? Please describe.**
question_answering_system.md

**Describe your suggestion**
CN translation needed.

**Additional reference**
Machine translation post editing (MTPE) is okay, but pure machine translation will not be accepted.
_You should have a certain level of proficiency in both Chinese and English in order to take this issue._

**Comment by YiyunNi** [comment]
Hi @iamartyaa , thanks for your interest in contributing to Milvus! I have updated the issue description with more details. Please feel free to let me know if you are still willing to take this issue.

**Comment by iamartyaa** [comment]
I have understood the issue and would like to work on it. Please assign it to me @YiyunNi .
