### ISSUE TITLE
[Suggestion] add how to develop milvus 2.0 on Mac os. 

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus-docs#558]
[compile_milvus2_macos (1).pdf](https://github.com/milvus-io/milvus-docs/files/7096715/compile_milvus2_macos.1.pdf)

**Comment by YiyunNi** [comment]
PR #577

**Comment by shanghaikid** [comment]
This is not about how to install milvus on mac. this doc is telling how to compile or develop milvus on mac os. 

https://milvus.io/docs/v2.0.0/install_macos.md#vscode

**Comment by YiyunNi** [comment]
This doc will be moved to the milvus repo instead.
