### ISSUE TITLE
[Suggestion]Translate tutorial - molecular_similarity_search.md into CN

### ISSUE THREAD

**Issue by YiyunNi** [milvus-io/milvus-docs#560]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

**Is there anything that's missing or inappropriate in the docs? Please describe.**
molecular_similarity_search.md

**Describe your suggestion**
Cn translation needed.

**Additional reference**
Machine translation post editing (MTPE) is okay, but pure machine translation will not be accepted.
_You should have a certain level of proficiency in both Chinese and English in order to take this issue._

**Comment by iamartyaa** [comment]
Hey @YiyunNi & @LocoRichard ,
I would like to work on this issue asap. Please assign it to me.

**Comment by YiyunNi** [comment]
@iamartyaa Thanks for your interest! I have updated this issue with more detailed instructions, please check it out and let me know if you still feel comfortable taking this issue.

**Comment by iamartyaa** [comment]
Ya I would like to work on the issue. Please assign it to me @YiyunNi .
