### ISSUE TITLE
[Suggestion]Translate gcp.md into CN

### ISSUE THREAD

**Issue by YiyunNi** [milvus-io/milvus-docs#565]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

**Is there anything that's missing or inappropriate in the docs? Please describe.**
gcp.md

**Describe your suggestion**
CN translation needed.

**Additional reference**
Machine translation post editing (MTPE) is okay, but pure machine translation will not be accepted.
_You should have a certain level of proficiency in both Chinese and English in order to take this issue._

**Comment by hlavu** [comment]
Hi, I would like to try working on this issue. Please assign it to me.

**Comment by YiyunNi** [comment]
> Hi, I would like to try working on this issue. Please assign it to me.

Thank you for showing your interest in contributing to Milvus! I have assigned this issue to you and you can start working on this now.

**Comment by hlavu** [comment]
Yes, sure. Thank you.
