### ISSUE TITLE
[Suggestion] Need doc about how to upgrade milvus

### ISSUE THREAD

**Issue by shanghaikid** [milvus-io/milvus-docs#570]
For example, I installed milvus 2.0rc4, What should I do in order to upgrade to 2.0rc5

**Comment by YiyunNi** [comment]
Please kindly suggest where to place this article in the menu. @shanghaikid

**Comment by shanghaikid** [comment]
Under Admin guide, thanks.

**Comment by shanghaikid** [comment]
Also, you can put a quick link on the installation page

**Comment by YiyunNi** [comment]
PR #599 #600
