### ISSUE TITLE
[Suggestion] Translate Reference - field_schema.md into CN

### ISSUE THREAD

**Issue by LocoRichard** [milvus-io/milvus-docs#583]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

**Is there anything that's missing or inappropriate in the docs? Please describe.**
field_schema.md in [Reference].

**Describe your suggestion**
Translate Reference - field_schema.md into CN

**Additional reference**
Machine translation post editing (MTPE) is okay, but pure machine translation will not be accepted.
_You should have a certain level of proficiency in both Chinese and English in order to take this issue._

**Comment by akashkarthikm** [comment]
Hey I would like to work on this issue, please assign it to me
