### ISSUE TITLE
[Suggestion] Translate Reference - collection_schema.md into CN

### ISSUE THREAD

**Issue by LocoRichard** [milvus-io/milvus-docs#584]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

**Is there anything that's missing or inappropriate in the docs? Please describe.**
collection_schema.md in [Reference].

**Describe your suggestion**
Translate Reference - collection_schema.md into CN

**Additional reference**
Machine translation post editing (MTPE) is okay, but pure machine translation will not be accepted.
_You should have a certain level of proficiency in both Chinese and English in order to take this issue._

**Comment by kartikcho** [comment]
Hey @LocoRichard are you looking for PRs that run the document through an EN to CN translation program or a rewrite from someone comfortable with CN?

If it's the former, could you assign this to me?

**Comment by LocoRichard** [comment]
@kartikcho Thank you for your interest in contributing to Milvus. Currently, we want someone who can deal with CN translation more professionally. Therefore, translation using program is not what we are looking for now. But please stay tuned. We may update some more issues that suit you!

**Comment by LocoRichard** [comment]
Hi @kartikcho , if you are still interested in contributing to us, there are some API- and doc-related issues in Milvus Go SDK repo. Check if there is any that you can work on in [Milvus Go SDK Hacktoberfest issues](https://github.com/milvus-io/milvus-sdk-go/issues?q=is%3Aopen+is%3Aissue+label%3AHACKTOBERFEST).

**Comment by kartikcho** [comment]
Thanks, I'll take a look at them!

**Comment by daniel-shuy** [comment]
I've created a PR at #752. Disclaimer: Chinese is not my primary language (English is), but I am proficient enough to read and write in Chinese.
