### ISSUE TITLE
[Suggestion] Update the CN translation of glossary

### ISSUE THREAD

**Issue by YiyunNi** [milvus-io/milvus-docs#593]
EN glossary has been updated. Please update the Chinese translation accordingly.

**Terms pending update and translation to CN are:**
Dependency
Log broker
Log sequence
Log subscriber
PChannel
Schema
Unstructured data
VChannel
Vector embedding
Vector similarity search

**Note:**
Machine translation post editing (MTPE) is okay, but pure machine translation will not be accepted.
_You should have a certain level of proficiency in both Chinese and English in order to take this issue._

**Comment by dahiya-code** [comment]
@YiyunNi could you assign this issue to me!

**Comment by YiyunNi** [comment]
@dahiya-code 
Hi, thanks for showing your interest! I have updated the issue description with more detailed instructions. Please feel free to let me know if you still would love to take this one.

**Comment by Rutam21** [comment]
@YiyunNi I can see that these are a few terms only. So, it shouldn't be a problem to figure out the translations. I would love to try this one and once done would really appreciate it if you can review and suggest changes if required.

**Comment by YiyunNi** [comment]
Hi @Rutam21 , thank you for showing your interest in contributing! We require certain level of proficiency in Chinese for this translation task. Are you comfortable with that? If yes, I can assign this issue to you.
