### ISSUE TITLE
[ERROR] Dead link in Milvus website 1.1 branch

### ISSUE THREAD

**Issue by ss892714028** [milvus-io/milvus-docs#595]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

**Where is the error**
What is the URL/path of the document related to this issue?
An user reported this in our wechat group. The links in this page are dead.
https://milvus.io/cn/docs/v1.1.1/data_manage.md#%E6%95%B0%E6%8D%AE%E7%AE%A1%E7%90%86%E7%9B%B8%E5%85%B3%E5%8D%9A%E5%AE%A2

**How would you like to improve it**

**Screenshots**

**Comment by LocoRichard** [comment]
Fix via #597 
#598
