### ISSUE TITLE
[Suggestion] Separate code and output

### ISSUE THREAD

**Issue by LocoRichard** [milvus-io/milvus-docs#607]
All codes are written together with the output, causing confusion to new users.

**Comment by shanghaikid** [comment]
I don't think so. I think all code block should contains output, so that users can understand the result.

**Comment by LocoRichard** [comment]
> I don't think so. I think all code blocks should contain output, so that users can understand the result.

I don't intend to delete the output. I simply thought that they are better be presented in different code blocks

**Comment by shanghaikid** [comment]
> > I don't think so. I think all code blocks should contain output, so that users can understand the result.
> 
> I don't intend to delete the output. I simply thought that they are better presented in different code blocks

I see.
