### ISSUE TITLE
[Suggestion]Organize adopters in alphabetical order

### ISSUE THREAD

**Issue by claireyuw** [milvus-io/milvus-docs#609]
Adopters added later, starting from iYUNDONG, are not sorted in alphabetical order. 

https://milvus.io/docs/v2.0.0/milvus_adopters.md

**Comment by kartikcho** [comment]
/assign @kartikcho
(I'll push a PR in the next month for it to count towards the Hacktober contributions if it's alright!)

**Comment by iamartyaa** [comment]
Hey! Can you please assign this issue to me,
I would like to work on it.

**Comment by iamartyaa** [comment]
Hey @claireyuw !
Can you please assign this issue to me? I would like to work on it.

**Comment by iamartyaa** [comment]
I have created a Pull Request making all the necessary changes. 
Please acknowledge it @claireyuw .

**Comment by LocoRichard** [comment]
@iamartyaa I have assigned the issue to you. Thank you again!
