### ISSUE TITLE
[Suggestion] Add use of  parameters `shards_num` and `using` in example of creating collection

### ISSUE THREAD

**Issue by jaelgu** [milvus-io/milvus-docs#632]
- Add parameters `shards_num` and `using` in https://milvus.io/docs/v2.0.0/create.md (Create Collection - 1) with example values.
- Add notes that if they are optional and their default values. (Please double check with dev: shards_num = 2, using = 'default' as default)
- Maybe also add in https://milvus.io/api-reference/pymilvus/v2.0.0rc5/api/collection.html (APIs References > class pymilvus.Collection > Example)

**Comment by LocoRichard** [comment]
@jaelgu Thank you. Working on it.
