### ISSUE TITLE
[Suggestion]Translate azure.md into CN.

### ISSUE THREAD

**Issue by YiyunNi** [milvus-io/milvus-docs#671]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

**Is there anything that's missing or inappropriate in the docs? Please describe.**
azure.md

**Describe your suggestion**
Please translate this doc (under site/cn) into CN.

**Additional reference**
Machine translation post editing (MTPE) is okay, but pure machine translation will not be accepted.
_You should have a certain level of proficiency in both Chinese and English in order to take this issue._

**Comment by Aryamanz29** [comment]
hey @YiyunNi  I would like to work on this one

**Comment by Aryamanz29** [comment]
@YiyunNi  Done 🙂 #741
