### ISSUE TITLE
[QUESTION] Is it possible to keep no original embeddings?

### ISSUE THREAD

**Issue by kwang2049** [milvus-io/milvus-docs#692]
I am using Milvus with Pymilvus. The project has a tight budget for memory usage. However, it seems that in Milvus the original embeddings will be also stored with all of the index types, which will take a lot of memory. So is it possible to keep only the index without the original embeddings?

**Comment by claireyuw** [comment]
@xiaofan-luan

**Comment by xiaofan-luan** [comment]
@kwang2049 We don't really need to put all embeddings into memory, especially when you are using IVFPQ or miny compact index types. We also support to  retrieve original vector from disk, you will need some local ssd storage as a cache otherwise the performance will be bad.

**Comment by claireyuw** [comment]
@kwang2049 If you have other questions in the future, you can also post about them on [Milvus Community Forum](https://discuss.milvus.io/) to be answered more promptly!

**Comment by kwang2049** [comment]
@xiaofan-luan Sounds great. So how can one configure to tell the Milvus not to load the original embeddings into memory when IVFPQ is used? By default, it seems that the original ones are also loaded:

```
#### docker stats for 1M embeddings (768D) ####
FLAT:
Traceback (most recent call last):
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
ce98b46f9f09        milvus-standalone   6.00%               4.793GiB / 1.475TiB   0.32%               3.09GB / 3.12GB     942kB / 9GB         49

IVF_SQ8:
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O           PIDS
4342047c7734        milvus-standalone   5.02%               8.5GiB / 1.475TiB   0.56%               5.87GB / 3.83GB     827kB / 9.29GB      630

IVF_PQ (386, 8)
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
a2a86ff8ff1a        milvus-standalone   2125.68%            7.607GiB / 1.475TiB   0.50%               3.55GB / 3.13GB     65.5kB / 7.94GB     149
```

@claireyuw Thank you the US president :).

**Comment by LocoRichard** [comment]
Closing the issue
