### ISSUE TITLE
Create a Collection or Partition (create.md) doc update

### ISSUE THREAD

**Issue by claireyuw** [milvus-io/milvus-docs#696]
Re: https://milvus.io/docs/v2.0.0/create.md

**Issue**
It does not look good to have two notes back to back.

**Suggestion**
Move the second note (note about parameters) to under the intro and above the "Create a collection".

**Provide any screenshots for reference.**
![screenshot-20210930-101830](https://user-images.githubusercontent.com/83751381/135374888-336fb19a-c7d1-4f23-bae0-900b69127940.png)

**Comment by harishfalco** [comment]
Can you assign it to me? I am ready to work on this

**Comment by claireyuw** [comment]
@harishfalco I've assigned this issue to you. Feel free to let me know if the instructions are unclear. Thank you for contributing!

**Comment by harishfalco** [comment]
Sure @claireyuw . Should I make PR during hacktoberfest ?

**Comment by claireyuw** [comment]
> Sure @claireyuw . Should I make PR during hacktoberfest ?

You can submit your PR whenever you're ready, but we will wait until October to merge to make sure it counts toward your Hacktoberfest participation.

**Comment by harishfalco** [comment]
Can you brief me about the issue? Its unclear

**Comment by claireyuw** [comment]
Hi @harishfalco 
I've updated the instructions above.

**Comment by harishfalco** [comment]
@claireyuw Thanks for the update. Started working on it.

**Comment by tabhay563** [comment]
can i work on this issue

**Comment by ion05** [comment]
Can i work on this issue ?

**Comment by AnuragYadav365** [comment]
Is there anyone working on this issue currently! If not, @claireyuw you can assign this issue to me, so I can make a PR regarding the issue!

**Comment by harishfalco** [comment]
@claireyuw , Sorry For not being active.I will complete it today

**Comment by iamartyaa** [comment]
Hey @claireyuw  , I have understood the issue, could you please assign it to me if it hasn't been done yet? 
I will work on it as soon as possible.

**Comment by claireyuw** [comment]
@tabhay563 @iamartyaa @AnuragYadav365 @ion05 
Thank you all for showing initiative, but this issue has been assigned to @harishfalco. Feel free to check out other pending issues
