### ISSUE TITLE
[ERROR] Dead image in v1.1.1 monitor.md

### ISSUE THREAD

**Issue by ss892714028** [milvus-io/milvus-docs#701]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

**Where is the error**
https://milvus.io/cn/docs/v1.1.1/monitor.md

**Screenshots**
![image](https://user-images.githubusercontent.com/34635663/135044181-3bea79d2-eb9d-4580-9f71-7ab4485ff7b2.png)

**Comment by LocoRichard** [comment]
Fixed via #702 #703 #704 
Closing the issue
