### ISSUE TITLE
[Suggestion] Milvus 1.1.1: Must enable GPU for index type IVF_SQ8H

### ISSUE THREAD

**Issue by jaelgu** [milvus-io/milvus-docs#713]
Missing a note for the fact: must enable GPU for index type IVF_SQ8H.

Although Milvus uses both CPU and GPU for indexing & searching with IVF_SQ8H, you will get error when create index if GPU is disabled:
```
Status(code=1, message="Error in virtual void milvus::knowhere::IVFSQHybrid::Train(const DatasetPtr&, const Config&) at virtual void milvus::knowhere::IVFSQHybrid::Train(const DatasetPtr&, const Config&):50: Build IVFSQHybrid can't get gpu resource")
```
So I think there should be a note in doc to remind users to enable GPU for IVF_SQ8H.

**Comment by YiyunNi** [comment]
PR #724 #725 #726
