### ISSUE TITLE
[Suggestion]Update the CN translation of boolean.md according to the new EN doc.

### ISSUE THREAD

**Issue by YiyunNi** [milvus-io/milvus-docs#729]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

**Is there anything that's missing or inappropriate in the docs? Please describe.**
boolean.md under CN site folder

**Describe your suggestion**
The EN doc is updated. Please help update the CN translation accordingly. 

**Additional reference**
1. The updated parts include doc overview and content under the section "operators".
2. Machine translation post editing (MTPE) is okay, but pure machine translation will not be accepted.
_You should have a certain level of proficiency in both Chinese and English in order to take this issue._

**Comment by YiyunNi** [comment]
Hi @sreyan-ghosh, thank you for showing your interest in contributing to Milvus! I have reviewed your PR and it seems like you've only updated the overview part in the CN doc. However, the content under the section named "operators" also needs to be translated into Chinese. 

Plus, I have added more details to the issue description. **We do not accept pure machine translation but MTPE is okay.** Please take a look at the issue description and feel free to let me know if you still would like to take this issue.

**Comment by sreyan-ghosh** [comment]
I see. Then @YiyunNi I wouldn't be able to take this issue up, I saw the last change made to the `boolean.md` file and saw a link change so implemented that. Please close my PR. Sorry to have misunderstood.

**Comment by YiyunNi** [comment]
But thank you anyways! If you are still interested in contributing to Milvus, you can take a look at other non-translation issues that are still open and unassigned. @sreyan-ghosh

**Comment by noviicee** [comment]
I can try this.

**Comment by YiyunNi** [comment]
Hi @noviicee, thank you for your contribution. I have reviewed your PR and left several comments. Would you please revise the translation accordingly?

**Comment by noviicee** [comment]
> Hi @noviicee, thank you for your contribution. I have reviewed your PR and left several comments. Would you please revise the translation accordingly?

Sure thanks.
