### ISSUE TITLE
[Suggestion] Add and translate parameters in User Guide to CN

### ISSUE THREAD

**Issue by LocoRichard** [milvus-io/milvus-docs#731]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

**Is there anything that's missing or inappropriate in the docs? Please describe.**
Pages in Milvus 2.0.0 CN User Guide

**Describe your suggestion**
Please find all relevant parameters in corresponding EN pages, copy them to CN pages, and then translate them in CN.

**Additional reference**
Machine translation post editing (MTPE) is okay, but pure machine translation will not be accepted.
_You should have a certain level of proficiency in both Chinese and English in order to take this issue._

**Comment by Aryamanz29** [comment]
Hey @LocoRichard  I would like to work on this

**Comment by joremysh** [comment]
I can take this if no one else is working on it now

**Comment by joremysh** [comment]
@LocoRichard do you mean to update all the *.md files under /milvus-docs/site/en/userGuide?

and does "parameters" refer to the "collection" or "Field" in below picture?
![image](https://user-images.githubusercontent.com/7455516/136664679-fc319273-c1bb-4481-8738-14b80471fd43.png)

**Comment by LocoRichard** [comment]
@joremysh Yes, we hope that you can help us move all the parameter tables started with "Detailed Description" in all articles under `/en/userGuide` to '/zh-CN/userGuide` and translate them into CN.
It refers to parameters in the collapsable tables, which lack in the CN version.
Thank you so much!
