### ISSUE TITLE
v2.0.0 Release Notes (release_notes.md) Doc Missing an Intro

### ISSUE THREAD

**Issue by Rutam21** [milvus-io/milvus-docs#743]
**Issue**

Release Notes is missing an introduction

**Suggestion**

Add an introduction to summarize what the page is about.

**Comment by Rutam21** [comment]
@claireyuw This is another page that misses a summary at the top. I would be taking this up as well.

**Comment by claireyuw** [comment]
@Rutam21 Thank you for your interest in contributing to Milvus documentation! I've added the labels and you can go ahead.
