### ISSUE TITLE
Translate milvusdm_install.md into CN

### ISSUE THREAD

**Issue by YiyunNi** [milvus-io/milvus-docs#821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Topic

Please translate milvusdm_install.md into CN.

You can find the doc at site/zh-CN/migrate/milvusdm_install.md

> Machine translation post editing (MTPE) is okay, but pure machine translation will not be accepted.
> _You should have a certain level of proficiency in both Chinese and English in order to take this issue._

**Comment by YiyunNi** [comment]
> Can it be assigned to me? Thanks.

Thank you for showing your interest in contributing! I have assigned this issue to you and you can now start working on it. @swartz-k

**Comment by Ayushman00100** [comment]
@swartz-k can it be assiggned to me
