### ISSUE TITLE
[ERROR]: Incorrect note for "Create Indexes"

### ISSUE THREAD

**Issue by jaelgu** [milvus-io/milvus-docs#998]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

Incorrect note: https://milvus.io/docs/v2.0.0/index.md#Create-indexes

![image](https://user-images.githubusercontent.com/86251631/139639172-f8feba28-0b7e-4d5e-8655-ab4db70014c6.png)

The default value is 1024 instead of 2048.

### Suggestion

By default, Milvus does not index a segment with less than 1,024 rows. To change this number, configure `minSegmentSizeToEnableIndex` in root_coord.yaml.

**Comment by claireyuw** [comment]
Fix EN and CN.
